common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset_name: "wikitext"
  dataset_config_name: "wikitext-2-raw-v1"
  data_cache_dir: /app/.huggingface_cache/dataset/
  partition_method: "hetero"
  partition_alpha: 0.5
  dataset_streaming: True
  

model_args:
  model: "gpt2"
  model_cache_dir: /app/.huggingface_cache/model/

train_args:
  federated_optimizer: "split_nn"
  client_id_list: "[]"
  client_num_in_total: 2
  client_num_per_round: 2
  comm_round: 1
  epochs: 5
  batch_size: 256
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
  server_optimizer: sgd
  lr: 0.001
  server_lr: 0.001
  wd: 0.001
  ci: 0
  server_momentum: 0.9

validation_args:
  frequency_of_the_test: 1

device_args:
  worker_num: 3
  using_gpu: true
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_default

comm_args:
  backend: "MPI"
  is_mobile: 0


tracking_args:
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/fedml-client/fedml/logs/ and ~/fedml-server/fedml/logs/
  enable_wandb: false
  wandb_key: ee0b5f53d949c84cee7decbe7a629e63fb2f8408
  wandb_project: fedml
  wandb_name: fedml_torch_fedavg_mnist_lr
  using_mlops: false